services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: team_task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - team_task_manager_pg:/var/lib/postgresql/data

volumes:
  team_task_manager_pg:
